name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write


jobs:
  build-and-test:
    timeout-minutes: 60

    # Use 20.04 because it has gtk2 available to install
    runs-on: ubuntu-20.04

    env:
      DISPLAY: :0
      EMFSTORE_TEST_SERVER_ROOT_DIR: ${{ github.workspace }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Set up test files
      run: |
        echo $EMFSTORE_TEST_SERVER_ROOT_DIR
        mkdir -p $EMFSTORE_TEST_SERVER_ROOT_DIR/profiles/default_test/conf/
        cat <<EOT >> $EMFSTORE_TEST_SERVER_ROOT_DIR/profiles/default_test/conf/es.properties
        emfstore.startup.post.loadlistener=true
        emfstore.keystore.certificate.type=SunX509
        emfstore.accesscontrol.authentication.superuser.password.hash=f262c3daf9b9c8fd380bdf34a415ee01c38e423d956d4f9c732273cf51264783787415c3b6d8701f3416735a31b06b8330e0be0d17ae5361ef83de320f17ba84
        emfstore.accesscontrol.authentication.superuser.password.salt=8a0InZ2yZMss65zHJrdhOXU6CqF8EeFncdv7V29ZO4qD565i5deWWXIi7aRkYwbY2BWamdOYQGqoZeZiJHZ0BH1mteMIhu3eIG5D2twfVQtjetvf8kiLOMwnYDsk4HPq
        emfstore.keystore.alias=emfstoreServer
        emfstore.accesscontrol.authentication.policy=spfv
        emfstore.acceptedversions=any
        emfstore.validation.level=7
        emfstore.validation.exclude=
        emfstore.connection.rmi.encryption=true
        emfstore.startup.loadlistener=false
        emfstore.keystore.cipher.algorithm=RSA
        emfstore.keystore.password=123456
        emfstore.connection.xmlrpc.port=8080
        emfstore.validation=true
        emfstore.persistence.version.projectstate.everyxversions=50
        emfstore.accesscontrol.authentication.superuser=super
        emfstore.accesscontrol.session.timeout=1800000
        EOT
        cat $EMFSTORE_TEST_SERVER_ROOT_DIR/profiles/default_test/conf/es.properties
    - name: Install UI dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk2.0-0 metacity xvfb
    - name: Configure virtual display
      run: |
        sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
        sudo metacity --replace --sm-disable &
    - name: Build and Test
      run: mvn clean verify -Dcheckstyle.skip -P aggregateSites -f releng/emfstore-parent --no-transfer-progress
      timeout-minutes: 20
    - name: Publish JUnit Test Report
      uses: mikepenz/action-junit-report@4fa23552acda20a6a1d44f16224a90efbeb6c5f1
      if: always()
      with:
        report_paths: '**/TEST-*.xml'
        check_retries: true
        detailed_summary: true
        fail_on_failure: true
    - name: Archive all log files
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: '**.log'
        retention-days: 7
    - name: Archive P2 repository (CI)
      if: success() && github.event_name == 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        name: p2-repository
        path: releng/org.eclipse.emf.emfstore.p2repository/target/repository/
        retention-days: 3
    - name: Archive P2 repository (Push)
      if: success() && github.event_name == 'push'
      uses: actions/upload-artifact@v3
      with:
        name: p2-repository
        path: releng/org.eclipse.emf.emfstore.p2repository/target/repository/
        retention-days: 14
